<?php 
 $matriz_noticias = array
    (
        array(
            "Mercado",
            "Mercado de TI cresce 4,5% no Brasil em 2017, abaixo da média mundial",
            "O mercado de Tecnologia da Informação (TI) — que engloba hardware, software e serviços — cresceu apenas 4,5% no Brasil em 2017. Mesmo que os números sejam positivos, o setor comemora de forma tímida, pois ainda assim ficou abaixo da média mundial no período, que foi de 5,5%, segundo o Tele Síntese. O levantamento foi feito pela Associação Brasileira das Empresas de Software (ABES), em parceria com a firma de consultoria global IDC.",
            "https://img.ibxk.com.br//2018/03/28/28164134601319-t1200x480.jpg"),
        array(
            "Software",
            "Machine learning ajudando a manter a inovação na indústria",
            "O aprendizado de máquina – mais conhecido pela expressão em inglês machine learning – é uma das grandes revoluções da tecnologia. Juntamente com outras aplicações, como Internet das Coisas e Inteligência Artificial, o machine learning tem proporcionado mudanças profundas em alguns setores da indústria e ajudado a manter a inovação.",
            "https://img.ibxk.com.br///2017/12/19/19155726931155-t1200x480.jpg"),
        array(
            "Software",
            "App brasileiro converte textos impressos em sons para deficientes visuais",
            "O EyeFy é a grande novidade para ajudar as pessoas com deficiências visuais. O app, criado no Brasil, é gratuito e usa inteligência artificial e aprendizado de máquina para identificar as palavras e converter textos em sons, como uma leitura em voz alta. O software pode ajudar também as pessoas não alfabetizadas.",
            "https://img.ibxk.com.br///2018/09/11/11094753717002-t1200x480.jpg"),
        array(
            "Hardware",
            "AMD anuncia processadores Athlon com núcleo Zen e os novos Ryzen PRO",
            "A AMD anunciou uma nova linha de processadores Athlon com arquitetura Zen e novos modelos Ryzen PRO. Segundo a informação oficial, o objetivo da companhia é expandir sua atuação no mercado, indo de PCs de entrada, a sofisticadas estações de trabalho no mundo corporativo.",
            "https://img.ibxk.com.br///2018/09/10/10175905080123-t1200x480.jpg"), 
        array(
            "Software",
            "TikTok permite que usuários adicionem vídeos de reação sobre outros vídeos",
            "A TikTok, que se fundiu com a Musical.ly, está lançando um novo recurso que permitirá aos usuários adicionarem suas reações enquanto assistem a outros vídeos. No menu 'Compartilhar' do aplicativo, agora há uma nova opção chamada 'Reagir' e, quando você a seleciona, o aplicativo gravará suas reações enquanto você assiste a um vídeo. Além disso, você poderá movê-lo e posicioná-lo onde quiser na tela de seu smartphone.",
            "https://img.ibxk.com.br///2018/09/06/06164716963170-t1200x480.jpg"),
        array(
            "Hardware",
            "Nova impressora 3D da HP faz objetos de metal em escala industrial",
            "A HP movimentou o setor de impressão 3D com o anúncio de um novo modelo. Trata-se da Metal Jet, que como o nome já entrega é um dispositivo capaz de criar modelos em três dimensões totalmente de metal, em vez dos tradicionais materiais derivados do plástico. Segundo a fabricante, a Metal Jet tem um método de impressão 50 vezes mais eficiente que os já existentes, é mais veloz e traz um custo mais baixo comparado com outros sistemas de jateamento.",
            "https://img.ibxk.com.br//2018/09/10/10114525136032-t1200x480.jpg"), 
        array(
            "Mercado",
            "Ministério da Cultura vai investir R$ 100 mi em política pública para games",
            "Durante a Game XP, o ministro da Cultura, Sérgio Sá Leitão, revelou que o MinC vai criar uma política pública para o setor de games que terá um investimento de R$ 100 milhões – que serão distribuídos entre linhas estratégicas de desenvolvimento de jogos, desenvolvimento e produção de conteúdo em VR e AR, lançamento de novos títulos, aceleração de empresas do segmento, investimentos em mostras e festivais, infraestrutura e tecnologia, além de formação e capacitação.",
            "https://img.ibxk.com.br//2018/09/11/11082313062008-t1200x480.jpg"), 
        array(
            "Hardware",
            "Para competição mais acirrada, Intel confirma Adaptative Sync em GPU",
            "O futuro do mercado de placas de vídeo tem aumentado a expectativa a cada anúncio. A NVIDIA tem em suas placas a tecnologia Ray Tracing, nas GPUs de microarquitetura Turing; AMD, por outro lado, não teve anúncios de nenhuma tecnologia gráfica, porém promete trazer as primeiras GPU de 7 nm, o que pode significar aprimoramentos de energia e performance; a Intel, somente por ter anunciado a sua chegada com sistema gráfico dedicado, já garante surpresas.",
            "https://img.ibxk.com.br///2018/09/01/01233103985046-t1200x480.jpg"),         
        array(
            "Mercado",
            "Como as ‘novas tecnologias’ estão impactando o mundo?",
            "O futuro do mundo é o mais conectado possível. E não estamos falando apenas das simples vantagens de comunicação que a internet nos oferece através de nosso PC ou celular: como está ficando bastante claro mesmo hoje, várias tecnologias que antes pareceriam saídas de um filme de ficção científica estão, nos últimos anos, tomando o mercado, como o caso da inteligência artificial, do Blockchain ou mesmo do Big Data.",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg")
    ); 
?>